[package]
name = "cosmic-time"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "examples/*",
]

[dependencies]
iced = { path = "../iced/", features = [ "tokio" ] }
iced_native = { path = "../iced/native" }
iced_futures = { path = "../iced/futures" }
iced_core = { path = "../iced/core" }
# iced_style = "0.5.1"
iced_style = { path = "../iced/style" }
