[package]
name = "cosmic-time"
version = "0.1.1"
edition = "2021"
description = "An animation Crate for Iced and Cosmic DE"
license = "MIT"
repository = "https://github.com/pop-os/cosmic-time"
documentation = "https://docs.rs/cosmic-time"
keywords = ["gui", "animation", "interface", "widgets", "iced"]
categories = ["gui"]

[workspace]
members = [
    "examples/*",
]

[dependencies]
iced = { version = "0.8.0", features = [ "tokio" ] }
iced_native = "0.9.1"
iced_futures = "0.6.0"
iced_core = "0.8.1"
iced_style = "0.7.0"
