[package]
name = "cosmic-time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.6.0", features = [ "tokio" ] }
iced_native = "0.7.0"
iced_futures = "0.5"
iced_core = "0.6.2"
